name: Precommit
on: [push, pull_request]

jobs:
  Run_UT:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: git ls-tree
        run: |
          python3 -m unittest discover -p "*_test.py" ./

  Build_Wheel:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: |
          python3 setup.py sdist bdist_wheel

      - name: Build wheel
        run: |
          python3 setup.py sdist bdist_wheel
